import React, { useEffect, useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { useDispatch, useSelector } from 'react-redux';
import { fetchRecipes, fetchCategories } from '../redux/slices/recipeSlice';
import { motion } from 'framer-motion';
import { FiSearch, FiArrowRight, FiCheck, FiCpu, FiStar, FiChevronRight } from 'react-icons/fi';
import toast from 'react-hot-toast';
import { getRecipeImage } from '../utils/recipeHelper';

const Landing = () => {
  const navigate = useNavigate();
  const dispatch = useDispatch();

  const { recipes, categories, loading } = useSelector((state) => state.recipes);
  const [searchText, setSearchText] = useState('');
  const [newsletterEmail, setNewsletterEmail] = useState('');

  useEffect(() => {
    // Fetch initial datasets
    dispatch(fetchRecipes({ limit: 3, sortBy: 'popular' }));
    dispatch(fetchCategories());
  }, [dispatch]);

  const handleSearchSubmit = (e) => {
    e.preventDefault();
    if (searchText.trim()) {
      navigate(`/search?search=${encodeURIComponent(searchText.trim())}`);
    }
  };

  const handleNewsletterSubmit = (e) => {
    e.preventDefault();
    if (newsletterEmail.trim()) {
      toast.success(`Welcome to the club! Subscribed ${newsletterEmail}`);
      setNewsletterEmail('');
    }
  };

  // Fallback mock categories if database collection is empty
  const defaultCategories = [
    { name: 'Italian', description: 'Pasta, pizzas, and risottos', icon: 'IT', link: '/search?cuisine=Italian' },
    { name: 'Mexican', description: 'Tacos, burritos, and quesadillas', icon: 'MX', link: '/search?cuisine=Mexican' },
    { name: 'Indian', description: 'Curries, naans, and tandooris', icon: 'IN', link: '/search?cuisine=Indian' },
    { name: 'Asian', description: 'Stir-fries, sushis, and dim sums', icon: 'AS', link: '/search?cuisine=Asian' },
  ];

  // Mock testimonial quotes
  const testimonials = [
    {
      name: 'Chef David L.',
      role: 'Home Cook',
      quote: 'RecipeAI has transformed my weeknights! I just type whatever leftover ingredients I have in the fridge and in seconds I have a custom recipe.',
      rating: 5,
    },
    {
      name: 'Elena Rostova',
      role: 'Food Blogger',
      quote: 'The nutrition breakdowns and cooking tips generated by the AI are incredibly accurate. The PDF export for shopping lists is a lifesaver.',
      rating: 5,
    },
  ];

  return (
    <div className="space-y-20 pb-20">
      
      {/* 1. Hero Section */}
      <section className="relative overflow-hidden bg-gradient-to-br from-green-50/50 via-slate-50 to-amber-50/20 py-24 sm:py-32">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
            
            {/* Slogans */}
            <div className="lg:col-span-7 space-y-6 text-left">
              <motion.div
                initial={{ opacity: 0, y: -10 }}
                animate={{ opacity: 1, y: 0 }}
                className="inline-flex items-center gap-1.5 rounded-full bg-green-50 px-3 py-1 text-xs font-semibold text-primary"
              >
                <FiCpu /> Powered by Google Gemini AI
              </motion.div>
              
              <motion.h1
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.1 }}
                className="text-4xl sm:text-6xl font-extrabold tracking-tight text-slate-850 leading-none font-display"
              >
                Unlock AI-Powered <br />
                <span className="text-primary">Culinary Creations</span>
              </motion.h1>

              <motion.p
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.2 }}
                className="text-base sm:text-lg text-slate-500 max-w-xl leading-relaxed"
              >
                Enter your ingredients, cuisine style, and dietary specifications to generate customized recipes. Keep cooking smart, reduce food waste, and plan meals.
              </motion.p>

              {/* Search Bar */}
              <motion.form
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.3 }}
                onSubmit={handleSearchSubmit}
                className="flex items-center gap-2 max-w-md p-1.5 bg-white border border-slate-200 rounded-2xl shadow-soft"
              >
                <div className="relative flex-grow">
                  <input
                    type="text"
                    placeholder="Search recipes, ingredients..."
                    value={searchText}
                    onChange={(e) => setSearchText(e.target.value)}
                    className="w-full pl-10 pr-4 py-2 text-sm bg-transparent outline-none focus:ring-0"
                  />
                  <FiSearch className="absolute left-3.5 top-2.5 text-slate-450 h-4.5 w-4.5" />
                </div>
                <button
                  type="submit"
                  className="bg-primary hover:bg-primary-dark text-white font-semibold text-xs py-2 px-4 rounded-xl shadow-md transition-colors flex items-center gap-1.5"
                >
                  Search
                </button>
              </motion.form>
            </div>

            {/* Visual Hero Image mock */}
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: 0.3, duration: 0.5 }}
              className="lg:col-span-5 flex justify-center"
            >
              <div className="relative h-72 w-72 sm:h-96 sm:w-96 rounded-card shadow-premium border border-white bg-white overflow-hidden flex items-center justify-center p-6">
                <div className="absolute inset-0 bg-gradient-to-tr from-green-500/10 to-amber-500/5 z-0"></div>
                <div className="z-10 text-center space-y-4">
                  <div className="h-16 w-16 mx-auto rounded-2xl bg-primary/10 text-primary flex items-center justify-center font-bold text-2xl">AI</div>
                  <h3 className="text-xl font-bold text-slate-850">What's in your fridge?</h3>
                  <p className="text-xs text-slate-450">Tofu, Broccoli, Carrot, Garlic...</p>
                  <Link to="/generate" className="inline-flex items-center gap-1.5 bg-primary text-white text-xs font-semibold py-2 px-4 rounded-xl shadow-md hover:bg-primary-dark transition-colors">
                    Generate Recipe <FiArrowRight />
                  </Link>
                </div>
              </div>
            </motion.div>

          </div>
        </div>
      </section>

      {/* 2. Popular Categories */}
      <section className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="text-center space-y-3 mb-10">
          <h2 className="text-3xl font-bold tracking-tight text-slate-800 font-display">Explore Popular Categories</h2>
          <p className="text-slate-500 text-sm">Browse curated cuisines and meal courses</p>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
          {loading && categories.length === 0 ? (
            // Skeletons when loading
            [1, 2, 3, 4].map(idx => (
              <div key={idx} className="h-24 bg-white animate-pulse rounded-card border border-slate-100 shadow-sm"></div>
            ))
          ) : categories.length === 0 ? (
            // Fallback mock categories if DB is empty
            defaultCategories.map((cat, idx) => (
              <Link
                key={idx}
                to={cat.link}
                className="flex items-center gap-3 bg-white p-4 rounded-card border border-slate-100 shadow-sm hover:shadow-md hover:border-primary/20 transition-premium group"
              >
                <div className="h-10 w-10 flex items-center justify-center rounded-xl bg-green-50 text-primary group-hover:bg-primary group-hover:text-white transition-colors font-bold">
                  {cat.icon}
                </div>
                <div className="text-left">
                  <div className="font-bold text-slate-800 text-sm group-hover:text-primary transition-colors">{cat.name}</div>
                  <div className="text-[10px] text-slate-400 truncate max-w-[120px]">{cat.description}</div>
                </div>
              </Link>
            ))
          ) : (
            // Real backend categories
            categories.slice(0, 4).map((cat) => (
              <Link
                key={cat._id}
                to={`/search?category=${cat._id}`}
                className="flex items-center gap-3 bg-white p-4 rounded-card border border-slate-100 shadow-sm hover:shadow-md hover:border-primary/20 transition-premium group"
              >
                <div className="h-10 w-10 flex items-center justify-center rounded-xl bg-green-50 text-primary group-hover:bg-primary group-hover:text-white transition-colors font-bold">
                  {cat.name[0]}
                </div>
                <div className="text-left">
                  <div className="font-bold text-slate-800 text-sm group-hover:text-primary transition-colors">{cat.name}</div>
                  <div className="text-[10px] text-slate-400 truncate max-w-[120px]">{cat.description}</div>
                </div>
              </Link>
            ))
          )}
        </div>
      </section>

      {/* 3. Featured Recipes */}
      <section className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="flex items-end justify-between mb-10">
          <div className="text-left space-y-2">
            <h2 className="text-3xl font-bold tracking-tight text-slate-800 font-display">Featured Recipes</h2>
            <p className="text-slate-500 text-sm">Delicious recipes curated by our culinary AI and chef community</p>
          </div>
          <Link to="/search" className="hidden sm:flex items-center gap-1 text-sm font-semibold text-primary hover:underline">
            View all <FiChevronRight />
          </Link>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {loading ? (
            [1, 2, 3].map(idx => (
              <div key={idx} className="h-80 bg-white animate-pulse rounded-card border border-slate-100 shadow-sm"></div>
            ))
          ) : recipes.length === 0 ? (
            <div className="col-span-full py-12 text-center text-slate-400 text-sm">
              No recipes created yet. Be the first to generate one!
            </div>
          ) : (
            recipes.map((recipe) => (
              <div
                key={recipe._id}
                className="flex flex-col bg-white rounded-card border border-slate-100 shadow-sm overflow-hidden hover:shadow-md hover:-translate-y-1 transition-premium"
              >
                <div className="relative h-44 bg-slate-100 overflow-hidden flex items-center justify-center">
                  <img src={getRecipeImage(recipe)} alt={recipe.title} className="h-full w-full object-cover" />
                  {recipe.isAI && (
                    <span className="absolute top-3 left-3 bg-primary text-white text-[9px] font-bold px-2 py-0.5 rounded-full shadow-sm">AI Generated</span>
                  )}
                </div>
                <div className="p-5 flex flex-col flex-grow text-left space-y-3">
                  <h3 className="font-bold text-slate-800 text-base line-clamp-1 hover:text-primary">
                    <Link to={`/recipes/${recipe._id}`}>{recipe.title}</Link>
                  </h3>
                  <p className="text-xs text-slate-400 line-clamp-2 leading-relaxed">{recipe.description}</p>
                  
                  <div className="flex items-center justify-between pt-2 border-t border-slate-100 text-xs text-slate-500 mt-auto">
                    <span>{recipe.totalTime} mins</span>
                    <span>{recipe.difficulty}</span>
                    <span>{recipe.calories} kcal</span>
                  </div>
                </div>
              </div>
            ))
          )}
        </div>
      </section>

      {/* 4. AI Banner Section */}
      <section className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="relative overflow-hidden bg-primary text-white rounded-card shadow-soft p-8 sm:p-12">
          <div className="absolute right-0 bottom-0 opacity-10 font-bold text-9xl select-none select-none translate-x-12 translate-y-12">GEMINI</div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
            <div className="space-y-4 text-left">
              <h2 className="text-2xl sm:text-4xl font-bold font-display leading-tight">Got ingredients? <br />Let our AI write the recipe.</h2>
              <p className="text-xs sm:text-sm text-green-50 leading-relaxed max-w-md">
                Don't worry about meal preps anymore. Just select what you have in stock, configure spices and cooking styles, and download dynamically generated checklists.
              </p>
              <div className="flex items-center gap-4 pt-2">
                <Link to="/generate" className="bg-white hover:bg-slate-50 text-primary font-bold text-sm py-2 px-5 rounded-xl transition-all shadow-md flex items-center gap-1">
                  Start Generating <FiArrowRight />
                </Link>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4 text-left font-semibold text-xs text-green-50">
              <div className="flex items-center gap-2">
                <FiCheck className="text-white h-5 w-5 bg-white/20 p-1 rounded-full" /> No signup required to search
              </div>
              <div className="flex items-center gap-2">
                <FiCheck className="text-white h-5 w-5 bg-white/20 p-1 rounded-full" /> Nutrition analyzed
              </div>
              <div className="flex items-center gap-2">
                <FiCheck className="text-white h-5 w-5 bg-white/20 p-1 rounded-full" /> Weekly planners
              </div>
              <div className="flex items-center gap-2">
                <FiCheck className="text-white h-5 w-5 bg-white/20 p-1 rounded-full" /> Instant PDF download
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 5. Testimonials */}
      <section className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="text-center space-y-3 mb-10">
          <h2 className="text-3xl font-bold tracking-tight text-slate-800 font-display">Loved by Home Chefs</h2>
          <p className="text-slate-500 text-sm">Here is what our growing community has to say about RecipeAI</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {testimonials.map((item, idx) => (
            <div key={idx} className="bg-white border border-slate-100 shadow-sm p-6 rounded-card text-left space-y-4">
              <div className="flex items-center gap-1 text-amber-500">
                {[...Array(item.rating)].map((_, i) => <FiStar key={i} className="fill-amber-500 h-4 w-4" />)}
              </div>
              <p className="text-sm text-slate-500 italic leading-relaxed">"{item.quote}"</p>
              <div className="text-xs">
                <span className="font-bold text-slate-800 block">{item.name}</span>
                <span className="text-slate-400">{item.role}</span>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* 6. Newsletter Signup */}
      <section className="mx-auto max-w-3xl px-4 text-center space-y-6">
        <h2 className="text-2xl sm:text-3xl font-bold text-slate-800 font-display">Subscribe for AI Weekly Insights</h2>
        <p className="text-sm text-slate-500 leading-relaxed max-w-md mx-auto">
          Get notifications regarding newly created categories, trending recipes, and chef community highlights delivered straight to your inbox.
        </p>
        <form onSubmit={handleNewsletterSubmit} className="flex flex-col sm:flex-row items-center gap-2 justify-center max-w-md mx-auto">
          <input
            type="email"
            placeholder="chef@example.com"
            required
            value={newsletterEmail}
            onChange={(e) => setNewsletterEmail(e.target.value)}
            className="w-full sm:flex-grow border border-slate-200 bg-white rounded-xl px-4 py-2 text-sm focus:outline-none focus:border-primary"
          />
          <button
            type="submit"
            className="w-full sm:w-auto bg-primary hover:bg-primary-dark text-white font-semibold text-sm py-2 px-5 rounded-xl shadow-md transition-all shadow-primary/15 whitespace-nowrap"
          >
            Sign Me Up
          </button>
        </form>
      </section>

    </div>
  );
};

export default Landing;
